name: Apply Cloudflare Gateway Policies

on:
  workflow_dispatch: # Memungkinkan kamu menjalankan script secara manual dari tab Actions di GitHub
  schedule:
    - cron: '0 0 * * 1' # Berjalan otomatis setiap seminggu sekali (Hari Senin jam 00:00 UTC) untuk memastikan policy tetap sinkron

jobs:
  apply-policies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Menggunakan Node 24 (Node 20 sudah deprecated di runner GitHub)

      - name: Run Policy Apply Script
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_DNS_POLICY_ID: ${{ secrets.CF_DNS_POLICY_ID }}
          CF_HTTP_POLICY_ID: ${{ secrets.CF_HTTP_POLICY_ID }}
        run: node dns_http_updater.js
